 const products = [
  {
    "_id": "01",
    "Name": "Watch",
    "details": "Whether you're running errands or shopping the sales.",
    "image": "images/products/image-1.jpg",
    "url": "https://www.daraz.com",
    "category": ["fashion", "man", "luxury"],
    "offer_tag": null,
    "off": "20% off",
    "regular_price": "22156",
    "offer_price": "8548",
    "free_shipping": true,
    "created-date": "2015-03-25"
  },
  {
    "_id": "02",
    "Name": "Shirt",
    "details": "A stylish shirt for any occasion.",
    "image": "images/products/image-2.jpg",
    "url": "https://www.example.com",
    "category": ["fashion", "man"],
    "offer_tag": "New",
    "off": "15% off",
    "regular_price": "7999",
    "offer_price": "6799",
    "free_shipping": false,
    "created-date": "2015-03-25"
  },
  {
    "_id": "03",
    "Name": "Dress",
    "details": "Elegant and comfortable dress for special events.",
    "image": "images/products/image-3.jpg",
    "url": "https://www.samplestore.com",
    "category": ["fashion", "woman", "evening"],
    "offer_tag": "Bestseller",
    "off": "30% off",
    "regular_price": "15000",
    "offer_price": "10500",
    "free_shipping": true,
    "created-date": "2015-03-25"
  },
  {
    "_id": "04",
    "Name": "Sneakers",
    "details": "Stay comfortable and stylish with these sneakers.",
    "image": "images/products/image-4.jpg",
    "url": "https://www.sneakerstore.com",
    "category": ["fashion", "shoes", "man"],
    "offer_tag": "Limited Edition",
    "off": "10% off",
    "regular_price": "5000",
    "offer_price": "4500",
    "free_shipping": true,
    "created-date": "2015-03-25"
  },
  {
    "_id": "05",
    "Name": "Handbag",
    "details": "A fashionable and functional accessory for any outfit.",
    "image": "images/products/image-5.jpg",
    "url": "https://www.accessorystore.com",
    "category": ["fashion", "accessories", "woman"],
    "offer_tag": "Clearance",
    "off": "40% off",
    "regular_price": "12000",
    "offer_price": "7200",
    "free_shipping": false,
    "created-date": "2015-03-25"
  },
  {
    "_id": "06",
    "Name": "Jeans",
    "details": "Classic denim jeans for a timeless look.",
    "image": "images/products/image-6.jpg",
    "url": "https://www.denimstore.com",
    "category": ["fashion", "man", "casual"],
    "offer_tag": "Back to School",
    "off": "25% off",
    "regular_price": "6000",
    "offer_price": "4500",
    "free_shipping": true,
    "created-date": "2015-03-25"
  },
  {
    "_id": "07",
    "Name": "Earrings",
    "details": "Add a touch of elegance with these earrings.",
    "image": "images/products/image-7.jpg",
    "url": "https://www.jewelrystore.com",
    "category": ["fashion", "accessories", "woman"],
    "offer_tag": null,
    "off": "20% off",
    "regular_price": "2500",
    "offer_price": "2000",
    "free_shipping": true,
    "created-date": "2015-03-25"
  },
  {
    "_id": "08",
    "Name": "Tie",
    "details": "Complete your formal look with this stylish tie.",
    "image": "images/products/image-8.jpg",
    "url": "https://www.menswearstore.com",
    "category": ["fashion", "man", "formal"],
    "offer_tag": "Clearance",
    "off": "30% off",
    "regular_price": "1500",
    "offer_price": "1050",
    "free_shipping": false,
    "created-date": "2015-03-25"
  },
  {
    "_id": "09",
    "Name": "Skirt",
    "details": "A versatile skirt for any occasion.",
    "image": "images/products/image-9.jpg",
    "url": "https://www.clothingstore.com",
    "category": ["fashion", "woman", "casual"],
    "offer_tag": null,
    "off": "15% off",
    "regular_price": "4000",
    "offer_price": "3400",
    "free_shipping": true,
    "created-date": "2015-03-25"
  },
  {
    "_id": "10",
    "Name": "Hat",
    "details": "Stay stylish and protected from the sun with this hat.",
    "image": "images/products/image-10.jpg",
    "url": "https://www.hatstore.com",
    "category": ["fashion", "accessories"],
    "offer_tag": "Summer Essential",
    "off": "10% off",
    "regular_price": "800",
    "offer_price": "720",
    "free_shipping": true,
    "created-date": "2015-03-25"
  }
]


export default products